name: example-mailpit
services:
  phpserver:
    type: php:8.2
  smtpserver:
    type: mailpit
    sendFrom:
      - phpserver

proxy:
  smtpserver:
    - mailpit.lndo.site

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@4lando/mailpit": ../..
