name: lando-mailpit
services:
  appserver:
    type: lando
    image: php:8.2
  mailpit:
    type: mailpit
    sources:
      - appserver

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@4lando/mailpit": ../..
