name: example-mailpit
services:
  phpserver:
    type: php:8.2
  smtpserver:
    type: mailpit
    mailFrom:
      - phpserver

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/mailpit": ../..
