name: Integration Tests (Examples)

on:
  pull_request:
  workflow_dispatch:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        leia-test:
          - examples/basic
          - examples/advanced
        lando-version:
          - 3-stable
          - 3-edge
        os:
          - ubuntu-24.04
        node-version:
          - '20'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install NPM dependencies
        run: npm clean-install --production
      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v3
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            setup.skipCommonPlugins=true
            setup.plugins.@lando/mailpit=/home/runner/work/mailpit/mailpit
          telemetry: false
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
